media:
  input: uploads
  output: /uploads

content:
  - name: index
    label: Home Page
    type: file
    path: index.html
    format: code

  - name: careers
    label: Careers Page
    type: file
    path: careers.html
    format: code

  - name: contact
    label: Contact Us
    type: file
    path: contact-us.html
    format: code

  - name: partnerships
    label: Partnerships
    type: file
    path: partnerships.html
    format: code

  - name: privacy
    label: Privacy Policy
    type: file
    path: privacy-policy.html
    format: code

  - name: projects
    label: Projects
    type: file
    path: projects.html
    format: code